language: node_js
node_js:
- "node"
cache: npm
before_script: cd site
script:
- npm i -g now
- npm run deploy:ci
env:
  global:
    secure: CCG2HnoJ0LrFEpgLUkU01Dsv6U75ZrD0VIv+GX4FOB+wsiMqdJYyfKln68+PwUMO72rP41/LVbeP0Xw9W7mc99YEVRIbjB8QL2i44vMmIpQJATUUxtk5qz3GCS2Rfn0wXfwI7eYNuSIJJf0SGQu9xu6ATXz7opkHqNVpdkouYC5yL/93bRBuDmtd7b9XqhAOJ/3SArPJqi6nahExgrKtYZofJtPfQAqTr3dI1UT4aF/OEp6tHfaIkHLJ4o17ou9tZ+d9vECyGB8+YIooMI1ZmmAOqVi5BzPztdeoJvQYJ4DcDsTSl/7gJv9KO2WqIoHh2dxyJbR/vwS9UEL3EW05sqP2IYULcCb8MK9Ol0DnNI2Qo+9nTIC93P+rFD0Pmx8d3RNi81eUV5jkpchc8rBeRS7kg9TnhAINylQWYodaPns93JmgzKEP5eeCp5+4vNE9ViBQX3swspEjWu+2Z+7LI9JzzwIy+q3RuJTLGjX8fmjcDp+kwWe4s/856kW6AU31JKx2pu63hz8vNC/T9LzK66CD2K5t4oBWmftgKuHwD/C4t8JHoxPEGUyGhFFAyrHhJHfcEWhjgk9rTuwLwUFehGL2JXAWL1N5VzSfJ5nNwiXcCpommWglXhvPQBQiETfQ60NurqT4mKeRjEXtFNjXMMUK60QI3lDzc4MtO5abcdw=
