language: node_js
node_js:
- node
cache: npm
before_script: cd site
script:
- npm install
- npm run test
- npm run codecov
- npm i -g now
- npm run deploy:ci
after_script:
- npm run alias
env:
  global:
  - secure: CCG2HnoJ0LrFEpgLUkU01Dsv6U75ZrD0VIv+GX4FOB+wsiMqdJYyfKln68+PwUMO72rP41/LVbeP0Xw9W7mc99YEVRIbjB8QL2i44vMmIpQJATUUxtk5qz3GCS2Rfn0wXfwI7eYNuSIJJf0SGQu9xu6ATXz7opkHqNVpdkouYC5yL/93bRBuDmtd7b9XqhAOJ/3SArPJqi6nahExgrKtYZofJtPfQAqTr3dI1UT4aF/OEp6tHfaIkHLJ4o17ou9tZ+d9vECyGB8+YIooMI1ZmmAOqVi5BzPztdeoJvQYJ4DcDsTSl/7gJv9KO2WqIoHh2dxyJbR/vwS9UEL3EW05sqP2IYULcCb8MK9Ol0DnNI2Qo+9nTIC93P+rFD0Pmx8d3RNi81eUV5jkpchc8rBeRS7kg9TnhAINylQWYodaPns93JmgzKEP5eeCp5+4vNE9ViBQX3swspEjWu+2Z+7LI9JzzwIy+q3RuJTLGjX8fmjcDp+kwWe4s/856kW6AU31JKx2pu63hz8vNC/T9LzK66CD2K5t4oBWmftgKuHwD/C4t8JHoxPEGUyGhFFAyrHhJHfcEWhjgk9rTuwLwUFehGL2JXAWL1N5VzSfJ5nNwiXcCpommWglXhvPQBQiETfQ60NurqT4mKeRjEXtFNjXMMUK60QI3lDzc4MtO5abcdw=
  - secure: JtSU0Kq1fBV33mHPW8BHbTvvUcT5AOSKFE4OeCsr20nN3DD9Mr6+jkD3N1rGDuSBUGPrJKlPvT3m73Uu92BhPDkEUM9veqrBlP7rwskjUaT3fjqgBVuWvn05BQA7fZsPuQ4tXFdDaqq2Tk2IHJ+uS1e9lOMqPhRnXTQV4VqhWnABaTD0KVJ5M/uWOBT0t1zO3IY9lnBuK6WAtNHiJXXAWLSRyRlNm/jZdDSamsdjynKf+/m/50x2nRiq+GyD72wqIiiDdeRBFAnKqy5bmUKlCjOzMJHCu2YmQBvpgYpWWXPf+S0L01/W2auuL1kDG2NoX283we2NExrH7fdJTEYor30b0O0LYS43t4FZUOCHhsyJkKwjrwEVGxwrczOkGp3w2ebEzxyDirnw/7qGVj3RmwdQwzWlKx6Dnk400KRZ2whWYeL3CFPQDD6k0BIIxDxMi7+uWrwqCXVqe5mCcJFDN09NZkmWCA3h/h0XlPt6TbWuxlivS7RlXMsGcXDb/qj6VTMVjyB8+/CAfofC4XhK2o0I7l4owZsWoweNsXFZLqG9IYxo3J81e6oHQJPqamoqIdD1w+BiJPB+NwZ+ilazI+Ufe751W3eVMzISFr0vQIsDIDExAcH0rBpUdpgkgV3ne51NdXQLB/vZ83fnqwiWhHPcQfQrTJiQyAbYyHXaur8=
