language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - cd site
# script:
  # - npm test
before_deploy:
  - npm install now --no-save
deploy:
  - provider: script
    script: now --public -e NODE_PATH="production" --token $NOW_TOKEN --no-verify && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
